name: test_cbo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0-190.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # Network
  dio: ^5.3.3
  internet_connection_checker: ^1.0.0+1
  # Local Storage
  shared_preferences: ^2.5.3
  # Functional Programming
  dartz: ^0.10.1
  # Dependency Injection
  get_it: ^7.6.4
  # UI utilities
  flutter_svg: ^2.0.5
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  geolocator: ^10.1.0
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  intl: ^0.19.0
  geocoding: ^3.0.0
  image: ^4.1.3
  shimmer: ^3.0.0
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_native_splash: ^2.3.7
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.0
  logging: ^1.2.0
  logger: ^2.0.2+1
  provider: ^6.1.5
  fl_chart: ^0.64.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mazta_logo.png
    - assets/images/schedule.png
    - assets/images/product.png
    - assets/images/report.png
  generate: true

# Konfigurasi Splash Screen
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/mazta_logo.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  android_12:
    # Icon untuk Android 12, pastikan ukurannya sesuai dengan pedoman
    image: assets/images/mazta_logo.png
    icon_background_color: "#FFFFFF"
    # Konfigurasi untuk mode gelap (opsional)
    image_dark: assets/images/mazta_logo.png
    icon_background_color_dark: "#FFFFFF"
  branding: assets/images/mazta_logo.png
  branding_mode: bottom
  info_plist_files:
    - "ios/Runner/Info.plist"
  # Tambahan konfigurasi untuk mengatasi masalah
  android_screen_orientation: portrait
