name: test_cbo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # Network
  dio: ^5.2.1+1
  internet_connection_checker: ^1.0.0+1
  # Local Storage
  shared_preferences: ^2.2.2
  # Functional Programming
  dartz: ^0.10.1
  # Dependency Injection
  get_it: ^7.6.4
  # UI utilities
  flutter_svg: ^2.0.5
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  geolocator: ^10.1.0
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  intl: ^0.19.0
  geocoding: ^3.0.0
  image: ^4.1.3
  shimmer: ^3.0.0
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mazta_logo.png
    - assets/images/schedule.png
    - assets/images/product.png
    - assets/images/report.png
  generate: true
